void Init( int width, int height );
void swap();
void clear();
int key( int& key, int& x, int& y );
void drawSquare( float x, float y, float width, float height );
void drawCircle( float x, float y, float r );
void drawPoint( float x, float y );
void drawText( float x, float y, const char* text );
void color( float r, float g, float b );
void close();
